#!/usr/bin/env lua
-- -*- lua -*-

require "makepb.recipes"

function make_srcpkgdir ( recipe_path )
    local srcobj = SrcPkgDir:new()
    local loader = RecipeLoader:new( recipe_path )
    loader:allow_classes{ autotools = AutotoolsClass }
    loader:run_recipe( srcobj )
    return srcobj
end

function strict_mode ( )
    local meta = { __index    = function ( env, name )
                                    error( "'" .. name .. "' is not defined",
                                           2 )
                                end;
                   __newindex = function ( env, name )
                                    error( "Attempted to define global '"
                                           .. name .. "'", 2 )
                                end }
    setmetatable( _G, meta )
end

strict_mode()

if #arg == 0 then
    print( "Give paths to 'recipes' as command line arguments!" )
    os.exit( 1 )
end

local i = 1
while i <= #arg do
    local srcobj = make_srcpkgdir( arg[i] )
    srcobj.pkgbuild:write_to( io.stdout )
    i = i + 1
end
